server:
  port: 8080
  servlet:
    context-path: /order_flow

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/flower_shop?zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false"
    username: root
    password: 170803
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        connection:
          zeroDateTimeBehavior: convertToNull

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds